<?php
echo '<div align="left" style="margin-top: 12px; width: 920px;">
		<div align="left">We\'re not even at the "this is just the tip of the iceberg" point with Meesto yet; there is a long and fantastic journey ahead.</div>
	</div><div align="left" style="margin-top: 32px; width: 900px;">
		<div align="left" class="p24">Our Current Goals and Focus</div>
		<div align="left" class="paragraph" style="margin-left: 24px; margin-top: 4px;">We plan to move swiftly but with precision. Currently, our main focus is on developing the Meesto community and maintaining the current version of Meesto. By the end of 2010 we hope to have an Open Source development community developing Meesto (2.0). The release of Meesto (2.0) will mark the first full-fledged Open Source cloud-based social networking tool. Our main goals with Meesto (2.0) will be converting Meesto over to an Open Source framework while increasing reliability, ease of use, compatibility and incorporating many other ideas which the community will discuss and develop as to what Meesto should be.<br />During the development of Meesto (2.0), we will also form a Nonprofit corporation and formalize our operations. We do plan to have a centralized headquarters in the Silicon Valley/Bay Area (of course, as we expand this could change). By mid-2011 we hope to have released Meesto (2.0) and have more formalized Nonporfit corporate operations. From there it\'s straight on through to Meesto (3.0).</div>
	</div><div align="left" style="margin-top: 32px; width: 900px;">
		<div align="left" class="p24">Thoughts On Expansion</div>
		<div align="left" class="paragraph" style="margin-left: 24px; margin-top: 4px;">Most companies, as they grow, become more focused on profit and lose touch with the people that actually use what they create. At Meesto, we take a different approach. Our goal is to become a Nonprofit company and full-fledged open source project so that we can do our absolute best to keep our focus on our sole mission of providing social tools that respect and empower the people that use them (not just with their data but with the actual tools). In fact, as Meesto grows and expands, it is this framework that will bring us even closer to the people that use the social tools we create. It is the Meesto community that will define what Meesto is and where it will go. This not only ensures a better tool for you today, it ensures that 20 years down the line you will still like what you\'re using because you\'re creating what you\'re using.</div>
	</div><div align="left" style="margin-top: 32px; width: 900px;">
		<div align="left" class="p24">Thinking More Long-Term</div>
		<div align="left" class="paragraph" style="margin-left: 24px; margin-top: 4px;">We\'re all about thinking long-term; we\'re big picture people. The decisions we make will involve the community and will utilize this type of thinking. Our plans for Meesto are, for the most part, fluid and will adjust according to what the community decides. However, we will never do anything to sacrifice our founding principles of respecting the people that use our tools and respecting their data. We never plan make any changes that don\'t coincide with this, but if we do, make sure we learn our lesson; but do it kindly. Remember, Meesto is what you make of it and you always have to power to change it. It\'s a new way of thinking but it\'s fantastic, if you think about it.</div>
	</div>';
?>