<?php
require_once('../externals/sessions/db_sessions.inc.php');
require_once ('../externals/general/includepaths.php');

$title = 'Help';
include ('../externals/header/header.php');

if (isset($_GET['action'])) {
	$action = escape_data($_GET['action']);	
} else {
	$action = '';	
}

if (isset($_GET['q'])) {
	$q = escape_data($_GET['q']);	
} else {
	$q = '';	
}

//main content
echo '<div align="left" style="width: 900px;">
<div align="left" class="p24">Meesto Help</div>
<div align="left" style="margin-top: 2px; padding-right: 24px; padding-bottom: 8px; border-bottom: 1px solid #C5C5C5;">Help information is generated by the community. All information and discussion here is public!<br/>Here you can search for answers to your questions, ask ones that haven\'t been asked, or search for questions you can answer. <span class="subtext" style="font-size: 14px;">(If you need to contact us via email you can do so via help@meesto.com)</span></div><div align="center" style="padding-bottom: 12px; padding-top: 12px; border-bottom: 1px solid #C5C5C5;">
	<form action="'.$baseincpat.'help.php" method="get">
		<table cellpadding="0" cellspacing="0"><tr><td align="left" valign="center">
			<input type="hidden" name="action" value="search" />
			<input type="text" name="q" size="72" maxlength="1000" autocomplete="off" onfocus="if (trim(this.value) == \'type here to search for an answer to your question....\') {this.value=\'\';};this.className=\'inputfocus\';" onblur="if (trim(this.value) == \'\') {this.value=\'type here to search for an answer to your question....\';this.className=\'inputplaceholder\';} else {this.className=\'inputplaceholderblur\';}" style="font-size: 18px;"';
				if ($q!=''){echo'value="'.$q.'"';}else{echo'class="inputplaceholder" value="type here to search for an answer to your question...."';}
			echo '/>
		</td><td align="left" valign="center" style="padding-left: 12px;">
			<input type="submit" value="ask"/>
		</td></tr></table>
	</form>
</div>
<div align="center" style="margin-top: 18px;">';
	
	if ($action=='search') {
		include('externalfiles/help/grab.php');
	} elseif (isset($_GET['htid'])&&($_GET['htid']!='')) {
		include('externalfiles/help/grabtopic.php');
	} else {
		echo '</div><div align="left" style="margin-top: 32px;">
			<div align="left" class="p24">Recently Asked Questions</div>
			<div align="left" class="paragraph" style="margin-left: 24px; margin-top: 4px;">';
				$results = mysql_query ("SELECT ht_id, msg FROM help_threads ORDER BY ht_id DESC LIMIT 15");
				while ($result = mysql_fetch_array ($results, MYSQL_ASSOC)) {
					$hid = $result['ht_id'];
					echo '<a href="'.$baseincpat.'help.php?htid='.$hid.'"><div align="left" class="p18" style="margin-top: 8px; padding-bottom: 4px; margin-bottom: 12px; border-bottom: 1px solid #C5C5C5;">
						<div align="left">'; if(strlen($result['msg'])>63){echo substr($result['msg'], 0, 63).'...'; }else{ echo $result['msg']; } echo'</div>
					</div></a>';
				}
			echo '</div>
		</div>';
	}
	
echo '</div>';

include ('../externals/header/footer.php');
?>