<?php
//main content
echo '<div align="left" class="subtext" style="margin-top: 4px; padding-left: 24px; padding-right: 24px;">Our goal is not to force you to agree to our terms. However, you should know the following before/while you use Meesto.</div>
<div align="left" style="margin-top: 24px; line-height: 32px;">
	<div align="left" class="p24" style="margin-top: 24px;">How Meesto Works</div>
	<div align="left" style="margin-left: 24px;">
		<div align="left" style="margin-top: 10px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" valign="top" style="padding-top: 14px;"><div style="width: 8px; height: 8px; background-color: #C5C5C5;"></div></td><td align="left" valign="top" style="padding-left: 12px;">Meesto operates like a Nonprofit Open Source company/project; though it is not (yet) officially so.</td></tr></table></div>
		<div align="left" style="margin-top: 12px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" valign="top" style="padding-top: 14px;"><div style="width: 8px; height: 8px; background-color: #C5C5C5;"></div></td><td align="left" valign="top" style="padding-left: 12px;">You, as a member of the collective community of Meesto users, are the controller of what happens with Meesto (Including this very document). Decisions are determined by a majority voting system. We encourage you to participate by contributing your skills, ideas, and general input.</td></tr></table></div>
		<div align="left" style="margin-top: 12px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" valign="top" style="padding-top: 14px;"><div style="width: 8px; height: 8px; background-color: #C5C5C5;"></div></td><td align="left" valign="top" style="padding-left: 12px;">You own and control your data.</td></tr></table></div>
	</div>
	<div align="left" class="p24" style="margin-top: 32px;">Things To Know</div>
	<div align="left" style="margin-left: 24px;">
		<div align="left" style="margin-top: 10px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" valign="top" style="padding-top: 14px;"><div style="width: 8px; height: 8px; background-color: #C5C5C5;"></div></td><td align="left" valign="top" style="padding-left: 12px;">What we mean by "you own your data"</td></tr></table></div>
			<div align="left" style="margin-top: 8px; margin-left: 24px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" valign="top" style="padding-top: 14px;"><div style="width: 8px; height: 8px; background-color: #C5C5C5;"></div></td><td align="left" valign="top" style="padding-left: 12px;">You are given complete control and ownership of your data and we will never access or distribute it without your express permission. However please understand that in a cloud-based environment it is impossible for you to wholly own your data, because it is stored on our servers. As such...</td></tr></table></div>
			<div align="left" style="margin-top: 8px; margin-left: 24px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" valign="top" style="padding-top: 14px;"><div style="width: 8px; height: 8px; background-color: #C5C5C5;"></div></td><td align="left" valign="top" style="padding-left: 12px;">We cannot guarantee 100% security and stability of your data &mdash; though we\'d like to. For your own protection do not upload or post highly sensitive, secretive, or classified material. In addition, we recommend that you always keep a personal copy of your data, such as photos, on a personal storage device, just as a fail-safe.</td></tr></table></div>
		<div align="left" style="margin-top: 12px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" valign="top" style="padding-top: 14px;"><div style="width: 8px; height: 8px; background-color: #C5C5C5;"></div></td><td align="left" valign="top" style="padding-left: 12px;">We reserve the right to make content that is found by the larger community to be harmful, offensive, pornographic, or otherwise inappropriate, unavailable. In such a scenario your data will be moved to a specified location where it will only be visible to you and you will be given a predetermined amount of time to retrieve your data before it is completely removed from our servers. Please understand that this is not a personal attack against you, it\'s to improve the experience of Meesto for everyone.</td></tr></table></div>
		<div align="left" style="margin-top: 12px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" valign="top" style="padding-top: 14px;"><div style="width: 8px; height: 8px; background-color: #C5C5C5;"></div></td><td align="left" valign="top" style="padding-left: 12px;">For your own legal protection, you are only allowed to upload and distribute data which you legally own. If we do need to enforce this requirement, you will be contacted and kept in-the-know for the entire process.</td></tr></table></div>
		<div align="left" style="margin-top: 12px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" valign="top" style="padding-top: 14px;"><div style="width: 8px; height: 8px; background-color: #C5C5C5;"></div></td><td align="left" valign="top" style="padding-left: 12px;">We encourage accountability. However, under no circumstances can you hold any members, staff, administrators, or officers of Meesto personally liable or responsible for matters resulting from the usage of Meesto by yourself or any another person/party..</td></tr></table></div>
	</div>
	<div align="left" class="p24" style="margin-top: 32px;">Who We Work With</div>
	<div align="left" style="margin-left: 24px;">
		<div align="left" style="margin-top: 10px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" valign="top" style="padding-top: 14px;"><div style="width: 8px; height: 8px; background-color: #C5C5C5;"></div></td><td align="left" valign="top" style="padding-left: 12px;">Our Web analytics, which is information about how many people view Meesto, is provided by <a href="http://www.google.com/analytics/">Google Analytics</a>. If you\'d like, you may review their <a href="http://www.google.com/analytics/tos.html">Terms of Service</a> and <a href="http://www.google.com/privacy.html">Privacy Policy</a>.</td></tr></table></div>
		<div align="left" style="margin-top: 12px;"><table cellpadding="0" cellspacing="0"><tr><td align="center" valign="top" style="padding-top: 14px;"><div style="width: 8px; height: 8px; background-color: #C5C5C5;"></div></td><td align="left" valign="top" style="padding-left: 12px;">Our Web hosting is purchased from <a href="http://www.networkredux.com/">Network Redux</a>. If you\'d like, you may review their <a href="http://www.networkredux.com/terms">Terms of Use</a>.</td></tr></table></div>
	</div>
</div>';
?>